export const authConstant = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT_REQUEST : "LOGOUT_REQUEST"
}

export const adminConstant = {
    ADMIN_REGISTER_REQUEST :"ADMIN_REGISTER_REQUEST",
    ADMIN_REGISTER_SUCCESS : "ADMIN_REGISTER_SUCCESS",
    ADMIN_REGISTER_FAILURE : "ADMIN_REGISTER_FAILURE"
}