export const authConstant = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT_REQUEST : "LOGOUT_REQUEST",
    LOGOUT_SUCCESS : "LOGOUT_SUCCESS",
    LOGOUT_FAILURE : " LOGOUT_FAILURE"
}

export const adminConstant = {
    ADMIN_REGISTER_REQUEST :"ADMIN_REGISTER_REQUEST",
    ADMIN_REGISTER_SUCCESS : "ADMIN_REGISTER_SUCCESS",
    ADMIN_REGISTER_FAILURE : "ADMIN_REGISTER_FAILURE"
}

export const categoryConstant = {
    GET_ALL_CATEGORY_REQUEST : "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS :"GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE :"GET_ALL_CATEGORY_FAILURE",
    ADD_NEW_CATEGORY_REQUEST : "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS : "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE : "ADD_NEW_CATEGORY_FAILURE",
}

export const productConstant = {
    GET_ALL_PRODUCT_REQUEST : "GET_ALL_PRODUCT_REQUEST",
    GET_ALL_PRODUCT_SUCCESS : "GET_ALL_PRODUCT_SUCCESS",
    GET_ALL_PRODUCT_FAILURE : "GET_ALL_PRODUCT_FAILURE",
    ADD_NEW_PRODUCT_REQUEST : "ADD_NEW_PRODUCT_REQUEST",
    ADD_NEW_PRODUCT_SUCCESS : "ADD_NEW_PRODUCT_SUCCESS",
    ADD_NEW_PRODUCT_FAILURE : "ADD_NEW_PRODUCT_FAILURE",
}

export const initialDataConstant = {
    GET_ALL_DATA_REQUEST : "GET_ALL_DATA_REQUEST",
    GET_ALL_DATA_SUCCESS :"GET_ALL_DATA_SUCCESS",
    GET_ALL_DATA_FAILURE :"GET_ALL_DATA_FAILURE",
}